FROM node:20-alpine AS deps

WORKDIR /srv
COPY package*.json ./
RUN npm ci --omit=dev

FROM node:20-alpine AS ddb-proxy

ENV NODE_ENV=production
EXPOSE 3000
WORKDIR /srv

COPY --from=deps /srv/node_modules ./node_modules
COPY . .

CMD [ "node", "index.js" ]
